# Render blueprint for ZOZH Coach Bot
# Place this file at the root of your repo as: render.yaml
# Docs: https://render.com/docs/infrastructure-as-code

services:
  - type: worker
    name: zozh-coach-bot
    env: python
    plan: starter            # starter | standard | pro ...
    region: oregon           # или frankfurt, singapore и т.д.
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      python bot.py
    autoDeploy: true
    envVars:
      - key: TG_TOKEN
        sync: false          # задай в Render → Environment
      - key: OPENAI_API_KEY
        sync: false
      - key: DEFAULT_TZ
        value: Asia/Almaty
      - key: MODEL_NAME
        value: gpt-4o-mini
      - key: DATABASE_URL
        value: sqlite+aiosqlite:///./data/zozh.db   # файл БД на диске ниже
    disk:
      name: zozh-sqlite
      mountPath: /opt/render/project/src/data
      sizeGB: 1

# --- Вариант с PostgreSQL вместо SQLite (опционально) ---
# databases:
#   - name: zozh-postgres
#     plan: starter
#     region: oregon
#
# # Если включишь БД выше, замени DATABASE_URL так:
# #   - key: DATABASE_URL
# #     fromDatabase:
# #       name: zozh-postgres
# #       property: connectionString
# #
# # И в коде приведи DSN к async-драйверу:
# #   raw = os.getenv("DATABASE_URL", "")
# #   if raw.startswith("postgres://"):
# #       raw = raw.replace("postgres://", "postgresql+asyncpg://", 1)
# #   DATABASE_URL = raw or "sqlite+aiosqlite:///./zozh.db"
